workspace:
  base: /srv/app
  path: src/github.com/kleister/kleister-ios

pipeline:



  notify-matrix:
    image: plugins/matrix:1
    pull: true
    secrets: [ matrix_roomid, matrix_username, matrix_password ]
    when:
      local: false
      events: [ push, tag ]
      status: [ changed, failure ]
