---
name: changes

"on":
  push:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Build changelog
        uses: actionhippie/calens@v1
        with:
          target: CHANGELOG.md

      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Kleister
          author_email: kleister@webhippie.de
          add: CHANGELOG.md
          message: "docs: automated changelog update"
          push: true
          commit: --signoff

...
